// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGD.Data;

#nullable disable

namespace SGD.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20251008135935_indexacaotable")]
    partial class indexacaotable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SGD.Models.AtividadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Atividade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubfuncaoModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubfuncaoModelId");

                    b.ToTable("Atividade");
                });

            modelBuilder.Entity("SGD.Models.DocumentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProtocoloId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProtocoloId");

                    b.HasIndex("TipoDocId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SGD.Models.EspecieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AtividadeModelId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeModelId");

                    b.ToTable("Especie");
                });

            modelBuilder.Entity("SGD.Models.EspecieTipoDoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("TipoDocumentalId");

                    b.ToTable("EspecieTipoDoc");
                });

            modelBuilder.Entity("SGD.Models.FluxoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DtFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SituacaoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("LoteId", "SituacaoId")
                        .IsUnique();

                    b.ToTable("FluxoLote");
                });

            modelBuilder.Entity("SGD.Models.FuncaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Funcao");
                });

            modelBuilder.Entity("SGD.Models.IndexacaoDocumentoModel", b =>
                {
                    b.Property<int>("MetadadoTipoDocId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetadadoTipoDocId", "DocumentoId", "LoteId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("LoteId");

                    b.ToTable("Indexacao");
                });

            modelBuilder.Entity("SGD.Models.LoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NumLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("SGD.Models.MetadadosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Metadados");
                });

            modelBuilder.Entity("SGD.Models.MetadadosTipoDocModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MetadadoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetadadoId");

                    b.HasIndex("TipoDocumentalId");

                    b.ToTable("MetadadosTipoDoc");
                });

            modelBuilder.Entity("SGD.Models.ParametrosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("SGD.Models.PermissoesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("SGD.Models.ProjetoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("SGD.Models.ProjetoPermissaoModel", b =>
                {
                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("ProjetoId", "PermissaoId");

                    b.ToTable("ProjetoPermissaoModel");
                });

            modelBuilder.Entity("SGD.Models.ProtocoloModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Etiqueta")
                        .HasColumnType("bigint");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("SGD.Models.SituacaoModel", b =>
                {
                    b.Property<int>("IdSituacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSituacao"), 1L, 1);

                    b.Property<string>("Caminho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdSituacaoAnterior")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("IdSituacao");

                    b.ToTable("Situacoes");
                });

            modelBuilder.Entity("SGD.Models.SubfuncaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<string>("Subfuncao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.ToTable("Subfuncao");
                });

            modelBuilder.Entity("SGD.Models.TipoDocumentalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumental");
                });

            modelBuilder.Entity("SGD.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Situação")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGD.Models.UsuarioPermissaoModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("UsuarioPermissoes");
                });

            modelBuilder.Entity("SGD.Models.UsuarioProjetoModel", b =>
                {
                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProjetoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioProjetos");
                });

            modelBuilder.Entity("SGD.Models.AtividadeModel", b =>
                {
                    b.HasOne("SGD.Models.SubfuncaoModel", null)
                        .WithMany("Atividades")
                        .HasForeignKey("SubfuncaoModelId");
                });

            modelBuilder.Entity("SGD.Models.DocumentoModel", b =>
                {
                    b.HasOne("SGD.Models.ProtocoloModel", "Protocolo")
                        .WithMany("Documentos")
                        .HasForeignKey("ProtocoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.TipoDocumentalModel", "TipoDoc")
                        .WithMany()
                        .HasForeignKey("TipoDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocolo");

                    b.Navigation("TipoDoc");
                });

            modelBuilder.Entity("SGD.Models.EspecieModel", b =>
                {
                    b.HasOne("SGD.Models.AtividadeModel", null)
                        .WithMany("Especies")
                        .HasForeignKey("AtividadeModelId");
                });

            modelBuilder.Entity("SGD.Models.EspecieTipoDoc", b =>
                {
                    b.HasOne("SGD.Models.EspecieModel", "Especie")
                        .WithMany("especieTiposDoc")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.TipoDocumentalModel", "TipoDocumental")
                        .WithMany()
                        .HasForeignKey("TipoDocumentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("TipoDocumental");
                });

            modelBuilder.Entity("SGD.Models.FluxoModel", b =>
                {
                    b.HasOne("SGD.Models.LoteModel", "Lote")
                        .WithMany("Fluxos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.SituacaoModel", "Situacao")
                        .WithMany()
                        .HasForeignKey("SituacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Situacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGD.Models.IndexacaoDocumentoModel", b =>
                {
                    b.HasOne("SGD.Models.DocumentoModel", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.LoteModel", "Lote")
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.MetadadosTipoDocModel", "MetadadoTipoDoc")
                        .WithMany()
                        .HasForeignKey("MetadadoTipoDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Lote");

                    b.Navigation("MetadadoTipoDoc");
                });

            modelBuilder.Entity("SGD.Models.LoteModel", b =>
                {
                    b.HasOne("SGD.Models.ProjetoModel", "Projeto")
                        .WithMany("Lote")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("SGD.Models.MetadadosTipoDocModel", b =>
                {
                    b.HasOne("SGD.Models.MetadadosModel", "Metadado")
                        .WithMany("MetadadosTipoDoc")
                        .HasForeignKey("MetadadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.TipoDocumentalModel", "TipoDocumental")
                        .WithMany("Metadados")
                        .HasForeignKey("TipoDocumentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadado");

                    b.Navigation("TipoDocumental");
                });

            modelBuilder.Entity("SGD.Models.ProjetoPermissaoModel", b =>
                {
                    b.HasOne("SGD.Models.PermissoesModel", "Permissao")
                        .WithMany("ProjetoPermissoes")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.ProjetoModel", "Projeto")
                        .WithMany("Permissoes")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("SGD.Models.ProtocoloModel", b =>
                {
                    b.HasOne("SGD.Models.LoteModel", "Lote")
                        .WithMany("Protocolos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("SGD.Models.SubfuncaoModel", b =>
                {
                    b.HasOne("SGD.Models.FuncaoModel", "Funcao")
                        .WithMany("Subfuncoes")
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("SGD.Models.UsuarioPermissaoModel", b =>
                {
                    b.HasOne("SGD.Models.PermissoesModel", "Permissao")
                        .WithMany("UsuariosPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.UsuarioModel", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGD.Models.UsuarioProjetoModel", b =>
                {
                    b.HasOne("SGD.Models.ProjetoModel", "Projeto")
                        .WithMany("UsuariosProjetos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.UsuarioModel", "Usuario")
                        .WithMany("UsuariosProjetos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGD.Models.AtividadeModel", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("SGD.Models.EspecieModel", b =>
                {
                    b.Navigation("especieTiposDoc");
                });

            modelBuilder.Entity("SGD.Models.FuncaoModel", b =>
                {
                    b.Navigation("Subfuncoes");
                });

            modelBuilder.Entity("SGD.Models.LoteModel", b =>
                {
                    b.Navigation("Fluxos");

                    b.Navigation("Protocolos");
                });

            modelBuilder.Entity("SGD.Models.MetadadosModel", b =>
                {
                    b.Navigation("MetadadosTipoDoc");
                });

            modelBuilder.Entity("SGD.Models.PermissoesModel", b =>
                {
                    b.Navigation("ProjetoPermissoes");

                    b.Navigation("UsuariosPermissoes");
                });

            modelBuilder.Entity("SGD.Models.ProjetoModel", b =>
                {
                    b.Navigation("Lote");

                    b.Navigation("Permissoes");

                    b.Navigation("UsuariosProjetos");
                });

            modelBuilder.Entity("SGD.Models.ProtocoloModel", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("SGD.Models.SubfuncaoModel", b =>
                {
                    b.Navigation("Atividades");
                });

            modelBuilder.Entity("SGD.Models.TipoDocumentalModel", b =>
                {
                    b.Navigation("Metadados");
                });

            modelBuilder.Entity("SGD.Models.UsuarioModel", b =>
                {
                    b.Navigation("UsuarioPermissoes");

                    b.Navigation("UsuariosProjetos");
                });
#pragma warning restore 612, 618
        }
    }
}
