// <auto-generated />
using System;
using SGD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SGD.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20250706122437_observacaoFluxo")]
    partial class observacaoFluxo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SGD.Models.DocumentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ProtocoloId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProtocoloId");

                    b.HasIndex("TipoDocId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SGD.Models.FluxoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DtFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DtInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Situacao")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("FluxoLote");
                });

            modelBuilder.Entity("SGD.Models.LoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NumLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Lote");
                });

            modelBuilder.Entity("SGD.Models.MetadadosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDocumentalModelId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TipoDocumentalModelId");

                    b.ToTable("Metadados");
                });

            modelBuilder.Entity("SGD.Models.PermissoesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("SGD.Models.ProjetoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("SGD.Models.ProjetoPermissaoModel", b =>
                {
                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("ProjetoId", "PermissaoId");

                    b.ToTable("ProjetoPermissaoModel");
                });

            modelBuilder.Entity("SGD.Models.ProtocoloModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Etiqueta")
                        .HasColumnType("bigint");

                    b.Property<int>("LoteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoteId");

                    b.ToTable("Protocolos");
                });

            modelBuilder.Entity("SGD.Models.TipoDocumentalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoDocumental");
                });

            modelBuilder.Entity("SGD.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("Situação")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGD.Models.UsuarioPermissaoModel", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("UsuarioPermissoes");
                });

            modelBuilder.Entity("SGD.Models.UsuarioProjetoModel", b =>
                {
                    b.Property<int>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProjetoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioProjetos");
                });

            modelBuilder.Entity("SGD.Models.DocumentoModel", b =>
                {
                    b.HasOne("SGD.Models.ProtocoloModel", "Protocolo")
                        .WithMany("Documentos")
                        .HasForeignKey("ProtocoloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.TipoDocumentalModel", "TipoDoc")
                        .WithMany()
                        .HasForeignKey("TipoDocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocolo");

                    b.Navigation("TipoDoc");
                });

            modelBuilder.Entity("SGD.Models.FluxoModel", b =>
                {
                    b.HasOne("SGD.Models.LoteModel", "Lote")
                        .WithMany("Fluxos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGD.Models.LoteModel", b =>
                {
                    b.HasOne("SGD.Models.ProjetoModel", "Projeto")
                        .WithMany("Lote")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("SGD.Models.MetadadosModel", b =>
                {
                    b.HasOne("SGD.Models.TipoDocumentalModel", null)
                        .WithMany("Metadados")
                        .HasForeignKey("TipoDocumentalModelId");
                });

            modelBuilder.Entity("SGD.Models.ProjetoPermissaoModel", b =>
                {
                    b.HasOne("SGD.Models.PermissoesModel", "Permissao")
                        .WithMany("ProjetoPermissoes")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.ProjetoModel", "Projeto")
                        .WithMany("Permissoes")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("SGD.Models.ProtocoloModel", b =>
                {
                    b.HasOne("SGD.Models.LoteModel", "Lote")
                        .WithMany("Protocolos")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("SGD.Models.UsuarioPermissaoModel", b =>
                {
                    b.HasOne("SGD.Models.PermissoesModel", "Permissao")
                        .WithMany("UsuariosPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.UsuarioModel", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGD.Models.UsuarioProjetoModel", b =>
                {
                    b.HasOne("SGD.Models.ProjetoModel", "Projeto")
                        .WithMany("UsuariosProjetos")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGD.Models.UsuarioModel", "Usuario")
                        .WithMany("UsuariosProjetos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGD.Models.LoteModel", b =>
                {
                    b.Navigation("Fluxos");

                    b.Navigation("Protocolos");
                });

            modelBuilder.Entity("SGD.Models.PermissoesModel", b =>
                {
                    b.Navigation("ProjetoPermissoes");

                    b.Navigation("UsuariosPermissoes");
                });

            modelBuilder.Entity("SGD.Models.ProjetoModel", b =>
                {
                    b.Navigation("Lote");

                    b.Navigation("Permissoes");

                    b.Navigation("UsuariosProjetos");
                });

            modelBuilder.Entity("SGD.Models.ProtocoloModel", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("SGD.Models.TipoDocumentalModel", b =>
                {
                    b.Navigation("Metadados");
                });

            modelBuilder.Entity("SGD.Models.UsuarioModel", b =>
                {
                    b.Navigation("UsuarioPermissoes");

                    b.Navigation("UsuariosProjetos");
                });
#pragma warning restore 612, 618
        }
    }
}
